### ISSUE TITLE
How do I set the api key in vimscript?

### ISSUE THREAD

**Issue by brycepg** [dense-analysis/neural#10]

**Comment by brycepg** [comment]
I ended up moving my vimrc to `~/.config/nvim/vimrc.vim` and then making my main rc file lua and sourcing that file:
```
local vimrc = vim.fn.stdpath("config") .. "/vimrc.vim" vim.cmd.source(vimrc)
require('neural').setup({
    open_ai = {
        api_key = 'my key'
    }
})
```

**Comment by Angelchev** [comment]
@brycepg You can use whatever environment variable you wish for the API key e.g.

-- Configure Neural like so in Lua
require('neural').setup({
    source = {
        openai = {
            api_key = vim.env.OPENAI_API_KEY,
        },
    },
})
