### ISSUE TITLE
curl error

### ISSUE THREAD

**Issue by DieracDelta** [dense-analysis/neural#12]
I'm getting `[Neural Error] -> curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)` when I run `C-N`. Any advice on how to debug this?

**Comment by Angelchev** [comment]
@DieracDelta Since the `v0.0.0 release`, the entire backend has been rewritten and the curl dependency is gone. As long as Vim/Neovim is compiled with python, everything should be good.

Any API errors will be printed cleanly on the editor for convenience
