### ISSUE TITLE
Running neural on range of lines

### ISSUE THREAD

**Issue by jschwarz89** [dense-analysis/neural#15]
Hi,

When I select a range of lines to ask a question about (such as shown in the example video) I'm getting, open executing "'<,'>:Neural": "E481: No range allowed". Similarly, I can't ask questions specifically on a selected code. What am I doing wrong?

**Comment by w0rp** [comment]
@jschwarz89 I broke it and I'll be fixing it again, most likely. I'm going to remove the video from the README as it's wrong, and we'll add a better one back again.

**Comment by w0rp** [comment]
I will also mention, I am wholly opposed to any feature that sends lines of code to a third party provider over IP protection concerns. I believe the plugin will be banned from the workplace if it makes it easy to leak IP. I would certainly ban it from my team if it behaved that way. I am investigating semantically analysing code and sending an intermediate representation to third parties so no code is ever shared implicitly with any third party with @Angelchev .

**Comment by w0rp** [comment]
See #16.
