### ISSUE TITLE
Use :Neural on visually selected words

### ISSUE THREAD

**Issue by ckangnz** [dense-analysis/neural#17]
Is there any way to write up the question or instruction first, and then ask the chat GPT rather than writing down everything in `:Neural ...` prompt?

**Comment by Konfekt** [comment]
A natural use would be asking ChatGPT to expand a visually selected comment, say describing a function, into the actual code (template).

**Comment by w0rp** [comment]
> A natural use would be asking ChatGPT to expand a visually selected comment, say describing a function, into the actual code (template).

Yes, this is a good use of that functionality. Bear in mind our requirements for privacy outlined in #16.

**Comment by Konfekt** [comment]
In the meanwhile, a mapping such as `nnoremap <leader>n :<c-u>Neural\ <c-r>*` would do.

**Comment by w0rp** [comment]
I have implemented `:NeuralExplain` for visual mode, which sends visually selected text to the selected data source and prints the explanation in the preview window. I've put in nearly bare minimum effort to redact passwords and secrets, as explained in the README. More work can be done on redacting passwords and secrets.

#31 will cover the use case of sending lines to an LLM that can be refined in a scratch buffer.
