### ISSUE TITLE
Integrate with Open Assistant

### ISSUE THREAD

**Issue by w0rp** [dense-analysis/neural#25]
https://open-assistant.io/

Open Assistant is a developing FOSS alternative to ChatGPT, and we should integrate with it. It should make it possible for us to run local models for better privacy. We will be able to share more information with local models for better results than we will see with OpenAI.

**Comment by Angelchev** [comment]
To quote OpenAssistant
> [OpenAssistant has finished!](https://open-assistant.io/bye)

Looks like they have changed direction and will not be hosting models through a public API.
