### ISSUE TITLE
Model selection

### ISSUE THREAD

**Issue by craigp** [dense-analysis/neural#28]
Looking at the README and source, it doesn't look like there's a config option to select the model you'd like to use - this would be a welcome addition I think.

**Comment by w0rp** [comment]
If you could provide some examples, that would be helpful. We'll look into this.

**Comment by w0rp** [comment]
I and @Angelchev were just discussing this, and we believe configuration of the following form would be appropriate.

```vim
let g:neural = {
\   'source': {
\       'openai': {
\           'temperature': 0.2,
\           'selected_model': 'text-davinci-003',
\           'model': {
\               'text-davinci-003' : {
\                   'temperature': 0.4,
\               },
\           },
\       },
\   },
\}
```

For every `source` `selected_model` lets you pick the model you want, and
`model` lets you specify overrides for settings per model, in case you want a 
different default `temperature`, `max_tokens`, etc. If keys aren't specificed 
for a specific model, we'll fall back on the defaults set for the `source`.

Additionally, we'll be adding some options to the Vim command so you can specify
a different temperature, max_tokens, and so on for just one job if you want 
something bit a longer or shorter, etc.

**Comment by wstewarttennes** [comment]
Any updates on model selection @w0rp ?

**Comment by w0rp** [comment]
I'll defer this one to @Angelchev .

**Comment by w0rp** [comment]
Thinking about this again, I think it will be much simpler to have a `model` key and edit the Neural code to have awareness of model types and exclude parameters from models where they don't make sense. Having different parameters for different models will just get complicated. We can make the default model for OpenAI the new `gpt-3.5-turbo-instruct`, which will replace `text-davinci-003`.

**Comment by w0rp** [comment]
You can now set the models to use for each source. See for example `:help g:neural.source.openai.model`. I'll open a separate issue for updating the default OpenAI model.
