### ISSUE TITLE
Continue respecting privacy, but allow a code context function.

### ISSUE THREAD

**Issue by DavidCincotta** [dense-analysis/neural#35]
I really respect the privacy first mentality. But to satisfy those who need context, using a descriptive function like :Neural.getcontext "prompt" could be very useful while maintaining your design pattern.

**Comment by w0rp** [comment]
I want a feature that sends information from the  editor, but only for local models. There's no issue with sending passwords, trade secrets, and so on to a process running on your local machine, or maybe also to a private organisation server over an encrypted connection.

I would like to set up connections for OpenAssistant and Llama.

**Comment by w0rp** [comment]
I'm going to say this is a duplicate of #16. The intentation for that issue is to track privacy-respecting analysis of code.
