### ISSUE TITLE
Is there a zIndex setting for the prompt ui?

### ISSUE THREAD

**Issue by guxuerui** [dense-analysis/neural#9]
When I use `:NeuralPrompt`, I can't see the pop-up ui. So is there a `zIndex` setting for the prompt ui?

Like this: 

![211492107-16d8d3f5-c066-4771-9f94-1bacef2aa05e](https://user-images.githubusercontent.com/3518142/219354100-501cecee-f087-4e3d-8418-0acd2abe21c1.png)

**Comment by w0rp** [comment]
@guxuerui To protect your API key, I have edited your image, cropped it while I was at it, and I deleted past revisions of your post. Be careful when sharing screenshots!

**Comment by guxuerui** [comment]
> @guxuerui To protect your API key, I have edited your image, cropped it while I was at it, and I deleted past revisions of your post. Be careful when sharing screenshots!

Thank you ! I will be careful.
